In [11]:
import numpy as np
import matplotlib.pyplot as plt

vec1 = np.array([-1., 4., -9.])
mat1 = np.array([[1., 3., 5.], [7., -9., 2.], [4., 6., 8.]])
mat1

array([[ 1.,  3.,  5.],
       [ 7., -9.,  2.],
       [ 4.,  6.,  8.]])

In [18]:
vec1

array([-1.,  4., -9.])

In [10]:
vec2 = (np.pi/4) * vec1
vec2

array([-0.78539816,  3.14159265, -7.06858347])

In [4]:
vec2 = np.cos(vec2)
vec2

array([ 0.70710678, -1.        ,  0.70710678])

In [8]:
vec3 = vec1 + 2*vec2
vec3

array([ 0.41421356,  2.        , -7.58578644])

In [13]:
vec4 = mat1 * vec3
vec4

array([[  0.41421356,   6.        , -37.92893219],
       [  2.89949494, -18.        , -15.17157288],
       [  1.65685425,  12.        , -60.6862915 ]])

In [14]:
np.transpose(mat1)

array([[ 1.,  7.,  4.],
       [ 3., -9.,  6.],
       [ 5.,  2.,  8.]])

In [15]:
np.linalg.det(mat1)

161.99999999999994

In [3]:
sum(mat1.diagonal())

0.0

In [16]:
vec1.min()

-9.0

In [17]:
np.where (vec1 == vec1.min())

(array([2], dtype=int64),)

In [20]:
mat1.min()

-9.0

In [20]:
A = np.array([[17, 24, 1, 8, 15],
             [23, 5, 7, 14, 16],
             [4, 6, 13, 20, 22],
             [10, 12, 19, 21, 3],
             [11, 18, 25, 2, 9]])
Arow = np.array (np.sum(A,-1))
Acoloumn = np.array (np.sum(A,-2))
if Arow.min() == Arow.max() == Acoloumn.min() == Acoloumn.max() == sum(np.diag(A)) == sum(np.diag (np.fliplr(A))):
    print('Array is Majic')
else:
    print('Array is not Majic')

Array is Majic


In [22]:
M = np.random.rand (10, 10)
M

array([[0.01022167, 0.40469858, 0.10968513, 0.1946261 , 0.73798205,
        0.85000909, 0.41594916, 0.90762085, 0.6417096 , 0.06705752],
       [0.73650149, 0.30536553, 0.80193822, 0.98899016, 0.8619975 ,
        0.93103981, 0.9412228 , 0.79275048, 0.58447168, 0.72104743],
       [0.61083233, 0.24641727, 0.84528429, 0.1109037 , 0.86603968,
        0.27717641, 0.03168498, 0.77204946, 0.44956959, 0.13312381],
       [0.2768986 , 0.46158199, 0.00537274, 0.35450895, 0.13786345,
        0.00480739, 0.21733972, 0.12584016, 0.07715048, 0.42253813],
       [0.93712436, 0.42888546, 0.52968141, 0.58990234, 0.84771578,
        0.57985934, 0.98565493, 0.61021718, 0.47498545, 0.00912876],
       [0.77022533, 0.15145352, 0.01861592, 0.81428159, 0.69887983,
        0.70473351, 0.9251243 , 0.05152425, 0.99253903, 0.66460288],
       [0.04082961, 0.86314511, 0.06512412, 0.89090584, 0.27922357,
        0.15653369, 0.457588  , 0.77018041, 0.04929072, 0.32482212],
       [0.12010715, 0.79364046, 0.5784481

In [23]:
MUL = M[:5, :5]
MUR = M[:5, 5:]
MLL = M[5:, :5]
MLR = M[5:, 5:]

MUL

array([[0.01022167, 0.40469858, 0.10968513, 0.1946261 , 0.73798205],
       [0.73650149, 0.30536553, 0.80193822, 0.98899016, 0.8619975 ],
       [0.61083233, 0.24641727, 0.84528429, 0.1109037 , 0.86603968],
       [0.2768986 , 0.46158199, 0.00537274, 0.35450895, 0.13786345],
       [0.93712436, 0.42888546, 0.52968141, 0.58990234, 0.84771578]])